export const SPRITES_ASSET_KEYS = {
    TEST_CARD: "TEST_CARD",
    TEST_MANA_CARD: "TEST_MANA_CARD",
    TEST_CARD_COUNT_CIRCLE: "TEST_CARD_COUNT_CIRCLE",
    TEST_CHARACTER_CARD: "TEST_CHARACTER_CARD"
};